language: node_js
node_js:
- '6.10'
deploy:
  provider: lambda
  function_name: billing-report
  region: ap-northeast-1
  role: arn:aws:iam::907331964011:role/TravisLambdaDeploy
  runtime: nodejs6.10
  handler_name: handler
  access_key_id:
    secure: dR9nvNMmPZMmbyjRS+0gAB5e+KL/37HnxqCLJvzenKsxvWXwPYngQOt8UV/xiraLWcPIaLh5LBw40a3jXbkgKXgvOZ5ZCbAD83k1Dyc5WTvlKsiku7ktHE70IKUN4fFzApH11L/w7Tg6indfQNnt3/yJYIkFRfk1wJVPJsZ/6OFeo+yKnkUrF26W78MtT0DoxGtiTh9d3ej4nVwMoOS3OznvxV330Wlb6l6DAYCgMxZNaDFaakgJU7OvrDyAtij2Yr/sKl9xY2qIHViy6NIQtBRoY7r/x8lLU6fQfV5e+jQ5hYMXp5I3FXxJ3QdLc1WZXUhJANp4mA75AG7REIXg2Y58E2LPAOGzWMbpYqmvNSu+xkH9uXXxypxBDs01526jzOzxhjtPuau3ApI3mpcvwshiO7/Hn4qypOQJYKcwI3/m6a2uY4VdrWrnEK9BiNfgc25BQ3+HBIl13oVTpSNzNaa5zrJTcojwFhQu338h74+UnqFJIJFSY/V/FjgrMJMwxWgAWdRacq18/XXhDK4q7lkuifE0rNls5PeOt+XLT/a2dr37yUkwczPtIdc+egM38UeeCKpkrVEBmN1uqSptE3PqGkhYgyURV/0YBZCij3cI+hvG2GfuHKzt4xReoHDYOtVUTjkLOkEFFa9I6pmYgWNXza7XmxDqifZfrVIdoiU=
  secret_access_key:
    secure: Fbovthr32nW8b/ddAgZBB94e8/z2AXVMqbtJrAR+yRGR1NfFWFJYJv6OqC+2kEM9Jje5i/C8KvQJ5sYrRcQlsEltjIjPjv1r5wRpb+Nx/1PXqTpLcNGPdBatB3NPYOp0fFzy9eFBGL46kZkqvVTrZJ6SCkYIjPA2KhhFnZjxShWlyfNwBhqB4vrK10etVKnz4qiV2Z9tvq8hWW9ddY6qQw3AvDJxdFaDOeUzQ4b4fq6fBcRJoRMKmG9zTb6L3/0FTj9grTgBqjCPYDf3qtdAWaIlRdOUkizypFcIXLqwqvKPORvKZ/Hcgyo4V+QIrl3wvrg/ojYhKYOTLmYZs9iI+vBwv9BT4xf7REYmslG+ecIqFkXiow2Iuov19E5j4i7kPLxKrkY42qoyDzS8IURQSfRTgErJ05QsaGqnvT7gW2XBGjkXn3bKgv+W3OxGlefoPZ31Btx2XlZ05vCILREcznxfH4/Iu1H+3AtZfd+PzTHc31swz8t9XouPxy/HoKI/GnPQkweu8+L2L7k0CJgnSgm+kI0b4ulgqhy3jj8qbIfQ5zXG3sZh21bhIBfUZBOnYoFzApaw+O+bay2liKYhxOQHCQgVvoMFUacBNbIyOpbI5TfxNLbTjnkN6M/eW1RfLZZPjv+o38u7yBQ/wZjvf1tcy710zzm6XJhW2MAk6aw=
