language: node_js
node_js:
- '6.10'
deploy:
  provider: lambda
  function_name: billing-report
  region: ap-northeast-1
  role: arn:aws:iam::907331964011:role/TravisLambdaDeploy
  runtime: nodejs6.10
  handler_name: handler
  access_key_id:
    secure: dR9nvNMmPZMmbyjRS+0gAB5e+KL/37HnxqCLJvzenKsxvWXwPYngQOt8UV/xiraLWcPIaLh5LBw40a3jXbkgKXgvOZ5ZCbAD83k1Dyc5WTvlKsiku7ktHE70IKUN4fFzApH11L/w7Tg6indfQNnt3/yJYIkFRfk1wJVPJsZ/6OFeo+yKnkUrF26W78MtT0DoxGtiTh9d3ej4nVwMoOS3OznvxV330Wlb6l6DAYCgMxZNaDFaakgJU7OvrDyAtij2Yr/sKl9xY2qIHViy6NIQtBRoY7r/x8lLU6fQfV5e+jQ5hYMXp5I3FXxJ3QdLc1WZXUhJANp4mA75AG7REIXg2Y58E2LPAOGzWMbpYqmvNSu+xkH9uXXxypxBDs01526jzOzxhjtPuau3ApI3mpcvwshiO7/Hn4qypOQJYKcwI3/m6a2uY4VdrWrnEK9BiNfgc25BQ3+HBIl13oVTpSNzNaa5zrJTcojwFhQu338h74+UnqFJIJFSY/V/FjgrMJMwxWgAWdRacq18/XXhDK4q7lkuifE0rNls5PeOt+XLT/a2dr37yUkwczPtIdc+egM38UeeCKpkrVEBmN1uqSptE3PqGkhYgyURV/0YBZCij3cI+hvG2GfuHKzt4xReoHDYOtVUTjkLOkEFFa9I6pmYgWNXza7XmxDqifZfrVIdoiU=
  secret_access_key:
    secure: C68OHAXQGq6stsCTHA1YSPdcG+YXIxS9omPhFLNK4fDqCtiichEmLpP/XfE3ZBhtFAzYQtFBF7yRJtahR90Fd6NGXNEpAIOOIfg22vJ6rzOGMf/eiMOK8JIVLVgnamBP4SB4E1hglaF3eygqUoYj8p9KvrX/VI8Fb+6K6FxHIGfH/Fqm3Od0795fnO1Xypn988GKJmw+Qp/4Eab0oe+29GhCBcPNHb6mDP2GkPgFlVouZZDWd2zie1Q7NlZuA9QHooIBg3IJz1geyEomCCRYsrgIJNIaaLkZU+qKkEOP8zjTaTFfaYnjOPQklgPqC4BAQBN/oj+x+pg8xzlO4jiAq06O3iyXPhsCECoGvqVRkYXgISB1s0I+T6bX2VLX58ER9Z6WGSxb7jUlJbAZNPfWBrrkPpgrCVBQ5zOt3K3ryy9IM2KOuoEH5M4d3Q4pIhQ694eRw6HkfGXwX+NpVvf/Aev9UeiLQXtk2cTFC3cCqWRq2AMs3LFBIR75qMwxB03JaTsXgrlPlEyDwJozSKmwUVpllInfCEELSGt/CaFNK3rH7piKrFcihoHF1hFqvYNXKqvUBfrZNt630bGieD+07LHdTFtVHJXDRaCLHloXPMVxQUgWQgfuGp+a5rQBySUfB7kbx/8ZA8y6XbU1damZDSWYJs4DY85PTwfixjzOF1Y=
